### ISSUE TITLE
project build fail

### ISSUE THREAD

**Issue by mseld** [MobileFirst-Platform-Developer-Center/SMSNotificationsAndroid#1]
class WLChallengeHandler is not exist
import com.worklight.wlclient.api.challengehandler.WLChallengeHandler;

**Comment by KapilPowar** [comment]
Hi,

May be its pointing to older Gradle file.
Could you please update your Gradle and try.

Thanks.

**Comment by IdanAdar** [comment]
@mseld: did you get a chance to review @KapilPowar's comment?

**Comment by mseld** [comment]
same problem @KapilPowar @IdanAdar

**Comment by NathanHazout** [comment]
@IdanAdar actually the error makes sense.

This sample seems to still be using `WLChallengeHandler`: https://github.com/MobileFirst-Platform-Developer-Center/SMSNotificationsAndroid/blob/release80/app/src/main/java/com/sample/pushnotificationsandroid/UserLoginChallengeHandler.java#L36

Which no longer exists, it was refactored to `SecurityCheckChallengeHandler` a long time ago ...

**Comment by mseld** [comment]
thanks @nasht00 , project build successfully after using SecurityCheckChallengeHandler  class

**Comment by IdanAdar** [comment]
I've opened an internal defect to handle this. Thanks for looking @nasht00.

**Comment by IdanAdar** [comment]
Fixed.
